package io.github.imonja.grpc.kt.common

import com.google.protobuf.ByteString
import com.google.protobuf.Message
import com.google.protobuf.Parser
import java.io.InputStream
import java.io.OutputStream

/**
 * Common interface for all Kotlin Protobuf messages generated by grpc-kt.
 *
 * @param J The type of the underlying Java Protobuf message.
 */
interface ProtoKtMessage<out J : Message> {
    /**
     * Serializes the message to a byte array.
     */
    fun toByteArray(): ByteArray

    /**
     * Serializes the message to a [ByteString].
     */
    fun toByteString(): ByteString

    /**
     * Writes the serialized message to an [OutputStream].
     */
    fun writeTo(output: OutputStream)
}

/**
 * Interface for companion objects of Kotlin Protobuf messages.
 *
 * @param K The type of the Kotlin representation of the message.
 * @param J The type of the underlying Java Protobuf message.
 */
interface ProtoKtCompanion<K : ProtoKtMessage<J>, J : Message> {
    /**
     * Deserializes a message from a byte array.
     */
    fun parseFrom(data: ByteArray): K

    /**
     * Deserializes a message from a [ByteString].
     */
    fun parseFrom(data: ByteString): K

    /**
     * Deserializes a message from an [InputStream].
     */
    fun parseFrom(input: InputStream): K

    /**
     * Returns a [Parser] for the Java Protobuf message.
     */
    fun javaParser(): Parser<J>

    /**
     * Returns a [Parser] for the Kotlin message.
     */
    fun kotlinParser(): Parser<K>
}
