package io.github.imonja.grpc.kt.common

import com.google.protobuf.ByteString

/**
 * Common interface for all Kotlin Protobuf messages generated by grpc-kt.
 */
interface ProtoKtMessage {
    /**
     * Serializes the message to a byte array.
     */
    fun toByteArray(): ByteArray

    /**
     * Serializes the message to a [ByteString].
     */
    fun toByteString(): ByteString
}
