package io.github.imonja.grpc.kt.toolkit

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import io.github.imonja.grpc.kt.toolkit.import.Import

fun FileSpec.Builder.addImport(import: Import) {
//    if (!import.packageName.contains(".pb.kt.")) {
//        addImport(import.packageName, import.simpleNames.joinToString("."))
//    }
    addImport(import.packageName, import.simpleNames.joinToString("."))
}

fun FileSpec.Builder.addAllImports(imports: Set<Import>) {
    imports.forEach { addImport(it) }
}

fun FunSpec.Builder.endControlFlowWithComma() {
    addCode("⇤")
    addStatement("},")
}

fun FileSpec.Builder.addGeneratedFileComments(fileDescriptorName: String) {
    addFileComment("Generated by the protocol buffer compiler.  DO NOT EDIT!\n")
    addFileComment("NO CHECKED-IN PROTOBUF GENCODE\n")
    addFileComment("\n")
    addFileComment("source: $fileDescriptorName\n")
//  addFileComment("Protobuf Java Version: $protobufVersion")
}
