name: CI Checks

on:
    pull_request:
    workflow_dispatch:
    workflow_call:
        inputs:
            run-ktlint:
                required: false
                type: boolean
                default: true
            run-tests:
                required: false
                type: boolean
                default: true

jobs:
    ci-base:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Run ktlint check
                if: ${{ inputs.run-ktlint == true || github.event_name != 'workflow_call' }}
                run: ./gradlew clean ktlintCheck

            -   name: Run tests
                if: ${{ inputs.run-tests == true || github.event_name != 'workflow_call' }}
                id: tests
                run: ./gradlew test

            -   name: Report Test Results
                if: ${{ always() && !cancelled() && steps.tests.outcome != 'skipped' && (inputs.run-tests == true || github.event_name != 'workflow_call') }}
                uses: dorny/test-reporter@v2
                with:
                    name: JUnit Tests
                    path: '**/build/test-results/test/TEST-*.xml'
                    reporter: java-junit
                    fail-on-error: false
