name: Ktlint Check

permissions:
    contents: read
    packages: write
    checks: write

on:
    pull_request:
    workflow_dispatch:

jobs:
    ktlint-check:
        uses: ./.github/workflows/ci-base.yml
        with:
            run-ktlint: true
            run-tests: false
