name: Publish Snapshot to GitHub Packages

permissions:
    contents: read
    packages: write
    checks: write

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    ci-checks:
        uses: ./.github/workflows/ci-checks.yml
        with:
            run-ktlint: true
            run-tests: true
    
    publish-snapshot:
        needs: ci-checks
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: gradle
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Publish to GitHub Packages
                run: ./gradlew publishAllPublicationsToGitHubRepository
                env:
                    GITHUB_USERNAME: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
