name: Publish Snapshot to GitHub Packages

permissions:
    contents: read
    packages: write
    checks: write

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    ci-checks:
        uses: ./.github/workflows/ci-checks.yml
        with:
            run-ktlint: true
            run-tests: true

    publish-snapshot:
        needs: ci-checks
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: gradle
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Publish to GitHub Packages
                run: ./gradlew publish
                env:
                    GITHUB_USERNAME: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-plugin-snapshot:
        needs: ci-checks
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: gradle
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Generate snapshot version
                run: |
                    COMMIT_SHA=$(git rev-parse --short HEAD)
                    TIMESTAMP=$(date +%Y%m%d.%H%M%S)
                    SNAPSHOT_VERSION="$TIMESTAMP-$COMMIT_SHA-SNAPSHOT"
                    echo "SNAPSHOT_VERSION=$SNAPSHOT_VERSION" >> $GITHUB_ENV
                    echo "Publishing plugin snapshot version: $SNAPSHOT_VERSION"
            -   name: Publish plugin to GitHub Packages
                run: ./gradlew :gradle-plugin:publishPluginMavenPublicationToGitHubRepository -PreleaseVersion=$SNAPSHOT_VERSION
                env:
                    GITHUB_USERNAME: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
