name: Publish Release to GitHub Packages

permissions:
    contents: read
    packages: write
    checks: write

on:
    push:
        tags:
            - '*'
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to release'
                required: true

jobs:
    ci-checks:
        uses: ./.github/workflows/ci-checks.yml
        with:
            run-ktlint: true
            run-tests: true
    
    setup-build:
        uses: ./.github/workflows/setup-build.yml
        with:
            version-input: ${{ github.event.inputs.version }}
    
    publish-github:
        needs: [ci-checks, setup-build]
        runs-on: ubuntu-latest
        steps:
            -   name: Publish to GitHub Packages
                run: ./gradlew publishAllPublicationsToGitHubRepository -PreleaseVersion=${{ needs.setup-build.outputs.version }}
                env:
                    GITHUB_USERNAME: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    
    publish-maven:
        needs: [ci-checks, setup-build]
        runs-on: ubuntu-latest
        steps:
            -   name: Publish to Maven Central
                run: ./gradlew publishToMavenCentral -PreleaseVersion=${{ needs.setup-build.outputs.version }}
                env:
                    MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                    SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
