name: Setup Build Environment

on:
    workflow_call:
        inputs:
            version-input:
                required: false
                type: string
                description: 'Manual version input for workflow_dispatch'
        outputs:
            version:
                description: 'Extracted version'
                value: ${{ jobs.setup.outputs.version }}

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get_version.outputs.version }}
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set up JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Extract version from tag
                id: get_version
                run: |
                    if [ "${{ github.event_name }}" == "push" ]; then
                      # Extract version from tag (e.g., 1.0.0)
                      TAG_VERSION=${GITHUB_REF#refs/tags/}
                      echo "Using version from tag: $TAG_VERSION"
                      echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
                    else
                      # Use manually provided version for workflow_dispatch
                      echo "Using manually provided version: ${{ inputs.version-input }}"
                      echo "version=${{ inputs.version-input }}" >> $GITHUB_OUTPUT
                    fi
