name: Run Tests

permissions:
    contents: read
    packages: write
    checks: write

on:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        uses: ./.github/workflows/ci-base.yml
        with:
            run-ktlint: false
            run-tests: true
